[package]
name = "day09_mirage_maintenance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
sdk = { path = "../sdk" }
winnow = "0.5.26"
