[workspace]
resolver = "2"
members = [
    "aoc01_trebuchet",
    "aoc02_cube_conundrum",
    "aoc03_gear_ratios",
    "aoc04_scratchcards",
    "aoc05_if_you_give",
    "aoc06_wait_for_it",
    "sdk"
]