[package]
name = "day18_lavaduct_lagoon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
hex = "0.4.3"
sdk = { path = "../sdk" }
